export const icons = {
  pipeline: 'Rocket',
  sources: 'PackageSearch',
  multiAccount: 'Store',
  translate: 'Languages',
  image: 'Image',
  category: 'Layers',
  serial: 'ListOrdered',
  tasks: 'ListChecks',
  duplicate: 'Copy',
  engine: 'Gauge',
  price: 'Coins',
  export: 'Table',
  account: 'KeyRound',
  cloudPool: 'Cloud',
  sync: 'MonitorSmartphone',
  assistant: 'Sparkles',
  privacy: 'ShieldCheck',
  faq: 'CircleHelp',
  cta: 'Download',
  support: 'LifeBuoy',
  wechat: 'MessageCircle',
  docs: 'BookOpen',
  footerLink: 'ArrowUpRight',
  permTabs: 'AppWindow',
  permActiveTab: 'MousePointerClick',
  permScripting: 'Zap',
  permStorage: 'HardDrive',
  permAlarms: 'AlarmClock',
  permNotifications: 'Bell',
  permContextMenus: 'MousePointerClick',
} as const;

export type IconKey = keyof typeof icons;
