/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBookForm: typeof import('./src/components/AddBookForm.vue')['default']
    ArticleToc: typeof import('./src/components/ArticleToc.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BasicFooter: typeof import('./src/components/basic/BasicFooter.vue')['default']
    BasicNav: typeof import('./src/components/basic/BasicNav.vue')['default']
    BasicNotifier: typeof import('./src/components/basic/BasicNotifier.vue')['default']
    BentoCalendar: typeof import('./src/components/bento/BentoCalendar.vue')['default']
    BentoCard: typeof import('./src/components/bento/BentoCard.vue')['default']
    BentoCat: typeof import('./src/components/bento/BentoCat.vue')['default']
    BentoClock: typeof import('./src/components/bento/BentoClock.vue')['default']
    BentoGreeting: typeof import('./src/components/bento/BentoGreeting.vue')['default']
    BentoMemo: typeof import('./src/components/bento/BentoMemo.vue')['default']
    BentoNav: typeof import('./src/components/bento/BentoNav.vue')['default']
    BentoNavCard: typeof import('./src/components/bento/BentoNavCard.vue')['default']
    BentoNewPost: typeof import('./src/components/bento/BentoNewPost.vue')['default']
    BentoPlaceholder: typeof import('./src/components/bento/BentoPlaceholder.vue')['default']
    BentoProfileCard: typeof import('./src/components/bento/BentoProfileCard.vue')['default']
    BentoReadingList: typeof import('./src/components/bento/BentoReadingList.vue')['default']
    BentoRecent: typeof import('./src/components/bento/BentoRecent.vue')['default']
    BentoRecommend: typeof import('./src/components/bento/BentoRecommend.vue')['default']
    BentoSocial: typeof import('./src/components/bento/BentoSocial.vue')['default']
    BentoTech: typeof import('./src/components/bento/BentoTech.vue')['default']
    BentoTechCard: typeof import('./src/components/bento/BentoTechCard.vue')['default']
    BookActionButtons: typeof import('./src/components/BookActionButtons.vue')['default']
    BookCard: typeof import('./src/components/BookCard.vue')['default']
    CategorySidebar: typeof import('./src/components/CategorySidebar.vue')['default']
    CommentForm: typeof import('./src/components/CommentForm.vue')['default']
    CommentItem: typeof import('./src/components/CommentItem.vue')['default']
    CommentsTab: typeof import('./src/components/CommentsTab.vue')['default']
    HomeSideBar: typeof import('./src/components/HomeSideBar.vue')['default']
    IconAnalytics: typeof import('./src/components/icons/IconAnalytics.vue')['default']
    IconClose: typeof import('./src/components/icons/IconClose.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconError: typeof import('./src/components/icons/IconError.vue')['default']
    IconInfo: typeof import('./src/components/icons/IconInfo.vue')['default']
    IconMemo: typeof import('./src/components/icons/IconMemo.vue')['default']
    IconPopular: typeof import('./src/components/icons/IconPopular.vue')['default']
    IconSuccess: typeof import('./src/components/icons/IconSuccess.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTags: typeof import('./src/components/icons/IconTags.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconTrend: typeof import('./src/components/icons/IconTrend.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    IconWarning: typeof import('./src/components/icons/IconWarning.vue')['default']
    ImgCat: typeof import('./src/components/icons/ImgCat.vue')['default']
    MemoModal: typeof import('./src/components/MemoModal.vue')['default']
    MemoSidebar: typeof import('./src/components/MemoSidebar.vue')['default']
    MessageBoard: typeof import('./src/components/MessageBoard.vue')['default']
    MessagesTab: typeof import('./src/components/MessagesTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerMonitor: typeof import('./src/components/ServerMonitor.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    TiptapEditor: typeof import('./src/components/TiptapEditor.vue')['default']
    TiptapToolbar: typeof import('./src/components/TiptapToolbar.vue')['default']
    ToastContainer: typeof import('./src/components/ToastContainer.vue')['default']
    TodoCard: typeof import('./src/components/bento/TodoCard.vue')['default']
  }
}
