"""添加RssInfo

Revision ID: 056d80d30f9d
Revises: 4d42db830046
Create Date: 2026-02-27 22:56:09.204100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "056d80d30f9d"
down_revision: Union[str, Sequence[str], None] = "4d42db830046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rss_info",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rss_url", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_rss_info_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rss_info")),
    )
    op.create_index(
        op.f("ix_rss_info_rss_url"), "rss_info", ["rss_url"], unique=False
    )
    op.create_index(
        op.f("ix_rss_info_user_id"), "rss_info", ["user_id"], unique=False
    )
    op.drop_column("user", "custom_footer")
    op.drop_column("user", "blog_title")
    op.drop_column("user", "custom_css")
    op.drop_column("user", "about")
    op.drop_column("user", "custom_js")
    op.drop_column("user", "blog_sub_title")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "blog_sub_title",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column("custom_js", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("about", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("custom_css", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user",
        sa.Column(
            "blog_title",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "custom_footer", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_rss_info_user_id"), table_name="rss_info")
    op.drop_index(op.f("ix_rss_info_rss_url"), table_name="rss_info")
    op.drop_table("rss_info")
    # ### end Alembic commands ###
