"""Add Subscription

Revision ID: 23d669e5197c
Revises: 258a91d2d1f9
Create Date: 2026-04-08 20:55:33.357587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23d669e5197c'
down_revision: Union[str, Sequence[str], None] = '258a91d2d1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('billing_cycle', sa.Enum('monthly', 'quarterly', 'yearly', name='billing_cycle_enum'), nullable=False),
    sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'canceled', 'paused', 'expired', name='subscription_status_enum'), nullable=False),
    sa.Column('reminder_config', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_subscription_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription'))
    )
    op.create_index(op.f('ix_subscription_created_at'), 'subscription', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_user_id'), 'subscription', ['user_id'], unique=False)
    op.drop_index(op.f('ix_message_board_name'), table_name='message_board')
    op.drop_table('message_board')
    op.add_column('profile', sa.Column('bark_device_key', sa.String(length=100), nullable=True))
    op.add_column('profile', sa.Column('feishu_webhook_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'feishu_webhook_url')
    op.drop_column('profile', 'bark_device_key')
    op.create_table('message_board',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_board'))
    )
    op.create_index(op.f('ix_message_board_name'), 'message_board', ['name'], unique=False)
    op.drop_index(op.f('ix_subscription_user_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_created_at'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
