"""modify Sub

Revision ID: 258a91d2d1f9
Revises: 6c860eab086c
Create Date: 2026-04-08 20:49:34.396318

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "258a91d2d1f9"
down_revision: str | Sequence[str] | None = "6c860eab086c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
