"""add github_id field to user model

Revision ID: 29a89d120d61
Revises: ca029d615c54
Create Date: 2026-03-14 21:15:06.483221

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29a89d120d61"
down_revision: str | Sequence[str] | None = "ca029d615c54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("github_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_user_github_id"), "user", ["github_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_github_id"), table_name="user")
    op.drop_column("user", "github_id")
    # ### end Alembic commands ###
