"""empty message

Revision ID: 30946bcb296f
Revises: 03fd9cf7f6f0
Create Date: 2026-02-22 20:36:56.406647

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30946bcb296f"
down_revision: str | Sequence[str] | None = "03fd9cf7f6f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signup_code_created_at"), table_name="signup_code")
    op.drop_table("signup_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signup_code",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "email",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "code", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signup_code")),
        sa.UniqueConstraint(
            "email",
            name=op.f("uq_signup_code_email"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_signup_code_created_at"),
        "signup_code",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
