"""Add Track detailed info

Revision ID: 37e0ae95456b
Revises: 8f3c1a4b9d2e
Create Date: 2026-03-08 14:24:32.239832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37e0ae95456b"
down_revision: Union[str, Sequence[str], None] = "8f3c1a4b9d2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "visitor_track",
        sa.Column("browser_name", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "visitor_track",
        sa.Column("browser_version", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "visitor_track",
        sa.Column("os_name", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "visitor_track",
        sa.Column("os_version", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "visitor_track", sa.Column("cpu", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "visitor_track",
        sa.Column("device_type", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visitor_track", "device_type")
    op.drop_column("visitor_track", "cpu")
    op.drop_column("visitor_track", "os_version")
    op.drop_column("visitor_track", "os_name")
    op.drop_column("visitor_track", "browser_version")
    op.drop_column("visitor_track", "browser_name")
    # ### end Alembic commands ###
