"""add log table

Revision ID: 3d6a7520206b
Revises: cbfc541baf4d
Create Date: 2026-06-21 00:00:28.069066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6a7520206b'
down_revision: Union[str, Sequence[str], None] = 'cbfc541baf4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log'))
    )
    op.create_index(op.f('ix_log_id'), 'log', ['id'], unique=False)
    op.create_index(op.f('ix_log_level'), 'log', ['level'], unique=False)
    op.create_index(op.f('ix_log_timestamp'), 'log', ['timestamp'], unique=False)
    op.create_index('ix_log_timestamp_level', 'log', ['timestamp', 'level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_log_timestamp_level', table_name='log')
    op.drop_index(op.f('ix_log_timestamp'), table_name='log')
    op.drop_index(op.f('ix_log_level'), table_name='log')
    op.drop_index(op.f('ix_log_id'), table_name='log')
    op.drop_table('log')
    # ### end Alembic commands ###
