"""添加track

Revision ID: 4d42db830046
Revises: 30946bcb296f
Create Date: 2026-02-26 17:44:30.106595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d42db830046'
down_revision: Union[str, Sequence[str], None] = '30946bcb296f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_track',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('page_url', sa.String(length=200), nullable=False),
    sa.Column('page_path', sa.String(length=200), nullable=False),
    sa.Column('referrer', sa.String(length=200), nullable=True),
    sa.Column('browser', sa.String(length=255), nullable=False),
    sa.Column('screen_resolution', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=False),
    sa.Column('visit_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitor_track'))
    )
    op.create_index(op.f('ix_visitor_track_ip_address'), 'visitor_track', ['ip_address'], unique=False)
    op.create_index(op.f('ix_visitor_track_visit_time'), 'visitor_track', ['visit_time'], unique=False)
    op.create_index(op.f('ix_visitor_track_visitor_id'), 'visitor_track', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_track_visitor_id'), table_name='visitor_track')
    op.drop_index(op.f('ix_visitor_track_visit_time'), table_name='visitor_track')
    op.drop_index(op.f('ix_visitor_track_ip_address'), table_name='visitor_track')
    op.drop_table('visitor_track')
    # ### end Alembic commands ###
