"""create device_track table

Revision ID: 62dbce97e75d
Revises: 23d669e5197c
Create Date: 2026-04-11 18:44:36.544015

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62dbce97e75d"
down_revision: str | Sequence[str] | None = "23d669e5197c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_track",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("purchase_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "retired", name="device_status_enum"),
            nullable=False,
        ),
        sa.Column("reminder_config", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_device_track_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_track")),
    )
    op.create_index(
        op.f("ix_device_track_created_at"),
        "device_track",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_device_track_user_id"),
        "device_track",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "subscription",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "subscription",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "subscription", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscription", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "subscription",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "subscription",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_index(op.f("ix_device_track_user_id"), table_name="device_track")
    op.drop_index(
        op.f("ix_device_track_created_at"), table_name="device_track"
    )
    op.drop_table("device_track")
    # ### end Alembic commands ###
