"""optimize tables: add composite indexes to visitor_track, fix User.name default, add Profile.user_id unique, fix UserBook.add_date nullable, remove redundant indexes

Revision ID: 6c860eab086c
Revises: eb6894753b21
Create Date: 2026-03-24 20:01:49.262253

"""

from collections.abc import Sequence

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c860eab086c"
down_revision: str | Sequence[str] | None = "eb6894753b21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_profile_user_id"), table_name="profile")
    op.create_unique_constraint(
        op.f("uq_profile_user_id"), "profile", ["user_id"]
    )
    op.drop_index(op.f("ix_user_github_id"), table_name="user")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.create_unique_constraint(
        op.f("uq_user_github_id"), "user", ["github_id"]
    )
    op.create_unique_constraint(op.f("uq_user_username"), "user", ["username"])
    op.alter_column(
        "user_book",
        "add_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_index(op.f("ix_user_book_book_id"), table_name="user_book")
    op.drop_index(op.f("ix_user_book_user_id"), table_name="user_book")
    op.create_index(
        "idx_visit_time_device_type",
        "visitor_track",
        ["visit_time", "device_type"],
        unique=False,
    )
    op.create_index(
        "idx_visit_time_ip_address",
        "visitor_track",
        ["visit_time", "ip_address"],
        unique=False,
    )
    op.create_index(
        "idx_visit_time_page_path",
        "visitor_track",
        ["visit_time", "page_path"],
        unique=False,
    )
    op.create_index(
        "idx_visit_time_visitor_id",
        "visitor_track",
        ["visit_time", "visitor_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_visit_time_visitor_id", table_name="visitor_track")
    op.drop_index("idx_visit_time_page_path", table_name="visitor_track")
    op.drop_index("idx_visit_time_ip_address", table_name="visitor_track")
    op.drop_index("idx_visit_time_device_type", table_name="visitor_track")
    op.create_index(
        op.f("ix_user_book_user_id"), "user_book", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_book_book_id"), "user_book", ["book_id"], unique=False
    )
    op.alter_column(
        "user_book",
        "add_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_constraint(op.f("uq_user_username"), "user", type_="unique")
    op.drop_constraint(op.f("uq_user_github_id"), "user", type_="unique")
    op.create_index(
        op.f("ix_user_username"), "user", ["username"], unique=True
    )
    op.create_index(
        op.f("ix_user_github_id"), "user", ["github_id"], unique=True
    )
    op.drop_constraint(op.f("uq_profile_user_id"), "profile", type_="unique")
    op.create_index(
        op.f("ix_profile_user_id"), "profile", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
