"""init Migration

Revision ID: 964a1ce1ebe8
Revises:
Create Date: 2026-02-21 22:06:16.619649

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "964a1ce1ebe8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
