"""Add PassKey

Revision ID: ca029d615c54
Revises: ca48f9c23d4c
Create Date: 2026-03-10 23:31:42.969875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca029d615c54"
down_revision: Union[str, Sequence[str], None] = "ca48f9c23d4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passkey_credential",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("credential_id", sa.String(length=255), nullable=False),
        sa.Column("public_key", sa.String(length=500), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_passkey_credential_user_id_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passkey_credential")),
        sa.UniqueConstraint(
            "credential_id", name=op.f("uq_passkey_credential_credential_id")
        ),
    )
    op.create_index(
        op.f("ix_passkey_credential_created_at"),
        "passkey_credential",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_passkey_credential_user_id"),
        "passkey_credential",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_passkey_credential_user_id"), table_name="passkey_credential"
    )
    op.drop_index(
        op.f("ix_passkey_credential_created_at"),
        table_name="passkey_credential",
    )
    op.drop_table("passkey_credential")
    # ### end Alembic commands ###
