"""Add Track Union Index

Revision ID: ca48f9c23d4c
Revises: 37e0ae95456b
Create Date: 2026-03-08 15:48:07.416923

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca48f9c23d4c"
down_revision: str | Sequence[str] | None = "37e0ae95456b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_visit_browser_stats",
        "visitor_track",
        ["visit_time", "browser_name", "browser_version"],
        unique=False,
    )
    op.create_index(
        "idx_visit_os_stats",
        "visitor_track",
        ["visit_time", "os_name", "os_version"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_visit_os_stats", table_name="visitor_track")
    op.drop_index("idx_visit_browser_stats", table_name="visitor_track")
    # ### end Alembic commands ###
