"""add exif column to gallery_image

Revision ID: cbfc541baf4d
Revises: 0103f6049668
Create Date: 2026-06-19 21:40:48.137865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfc541baf4d'
down_revision: Union[str, Sequence[str], None] = '0103f6049668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery_image', sa.Column('exif', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gallery_image', 'exif')
    # ### end Alembic commands ###
