"""Add GalleryImage model

Revision ID: f816f32028f6
Revises: 62dbce97e75d
Create Date: 2026-05-08 13:28:43.194651

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f816f32028f6"
down_revision: str | Sequence[str] | None = "62dbce97e75d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gallery_image",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=50), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_gallery_image_user_id_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gallery_image")),
    )
    op.create_index(
        op.f("ix_gallery_image_created_at"),
        "gallery_image",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gallery_image_sort_order"),
        "gallery_image",
        ["sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gallery_image_user_id"),
        "gallery_image",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gallery_image_user_id"), table_name="gallery_image")
    op.drop_index(
        op.f("ix_gallery_image_sort_order"), table_name="gallery_image"
    )
    op.drop_index(
        op.f("ix_gallery_image_created_at"), table_name="gallery_image"
    )
    op.drop_table("gallery_image")
    # ### end Alembic commands ###
