"""Add indexes to frequently queried fields

Revision ID: 3adf3dbb12a6
Revises: 9081d62a9ac4
Create Date: 2026-02-15 11:45:23.137757

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3adf3dbb12a6"
down_revision = "9081d62a9ac4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_profile_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("signup_code", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_signup_code_created_at"),
            ["created_at"],
            unique=False,
        )

    with op.batch_alter_table("user_book", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_book_add_date"), ["add_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_book_book_id"), ["book_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_book_update_date"),
            ["update_date"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_user_book_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_book", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_book_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_book_update_date"))
        batch_op.drop_index(batch_op.f("ix_user_book_book_id"))
        batch_op.drop_index(batch_op.f("ix_user_book_add_date"))

    with op.batch_alter_table("signup_code", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_signup_code_created_at"))

    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profile_user_id"))

    # ### end Alembic commands ###
