"""empty message

Revision ID: 7bc552614a9e
Revises: ebb25dc86c0d
Create Date: 2026-02-06 18:46:08.787348

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7bc552614a9e"
down_revision = "ebb25dc86c0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.Column("blog_title", sa.String(length=100), nullable=True),
        sa.Column("blog_sub_title", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=30), nullable=True),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("custom_footer", sa.Text(), nullable=True),
        sa.Column("custom_css", sa.Text(), nullable=True),
        sa.Column("custom_js", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin")),
    )
    with op.batch_alter_table("admin", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_admin_username"), ["username"], unique=True
        )

    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
        sa.UniqueConstraint("name", name=op.f("uq_category_name")),
    )
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_post_category_id_category"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post")),
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("author", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("site", sa.String(length=100), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("from_admin", sa.Boolean(), nullable=False),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("replied_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"], ["post.id"], name=op.f("fk_comment_post_id_post")
        ),
        sa.ForeignKeyConstraint(
            ["replied_id"],
            ["comment.id"],
            name=op.f("fk_comment_replied_id_comment"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment")
    op.drop_table("post")
    op.drop_table("category")
    with op.batch_alter_table("admin", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_username"))

    op.drop_table("admin")
    # ### end Alembic commands ###
