"""empty message

Revision ID: 9081d62a9ac4
Revises: 7bc552614a9e
Create Date: 2026-02-07 17:28:06.810413

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9081d62a9ac4"
down_revision = "7bc552614a9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("blog_title", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("blog_sub_title", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(sa.Column("about", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("custom_footer", sa.Text(), nullable=True)
        )
        batch_op.add_column(sa.Column("custom_css", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("custom_js", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("custom_js")
        batch_op.drop_column("custom_css")
        batch_op.drop_column("custom_footer")
        batch_op.drop_column("about")
        batch_op.drop_column("blog_sub_title")
        batch_op.drop_column("blog_title")

    # ### end Alembic commands ###
