"""empty message

Revision ID: cec5ac8f6893
Revises: 3adf3dbb12a6
Create Date: 2026-02-20 22:44:38.366480

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cec5ac8f6893"
down_revision = "3adf3dbb12a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_login_at", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("current_login_at", sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_login_ip", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column("current_login_ip", sa.String(length=100), nullable=True)
        )
        # add non-nullable fields with server defaults so existing rows are populated
        batch_op.add_column(
            sa.Column(
                "login_count", sa.Integer(), nullable=False, server_default="0"
            )
        )
        batch_op.add_column(
            sa.Column(
                "active",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
    # ### end Alembic commands ###

    # clean up server defaults if you prefer (optional)
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("login_count", server_default=None)
        batch_op.alter_column("active", server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("active")
        batch_op.drop_column("login_count")
        batch_op.drop_column("current_login_ip")
        batch_op.drop_column("last_login_ip")
        batch_op.drop_column("current_login_at")
        batch_op.drop_column("last_login_at")

    # ### end Alembic commands ###
