"""empty message

Revision ID: ebb25dc86c0d
Revises:
Create Date: 2026-02-06 01:24:58.340089

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ebb25dc86c0d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("author", sa.String(length=60), nullable=False),
        sa.Column("bookid", sa.String(length=50), nullable=True),
        sa.Column("cover", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book")),
        sa.UniqueConstraint("bookid", name=op.f("uq_book_bookid")),
    )
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_book_author"), ["author"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_book_title"), ["title"], unique=False
        )

    op.create_table(
        "message_board",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_board")),
    )
    with op.batch_alter_table("message_board", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_message_board_name"), ["name"], unique=False
        )

    op.create_table(
        "signup_code",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signup_code")),
        sa.UniqueConstraint("email", name=op.f("uq_signup_code_email")),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_name"), ["name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_username"), ["username"], unique=True
        )

    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("mobile", sa.String(length=15), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("photo", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_profile_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile")),
        sa.UniqueConstraint("email", name=op.f("uq_profile_email")),
    )
    op.create_table(
        "user_book",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("iscompleted", sa.Boolean(), nullable=False),
        sa.Column("add_date", sa.DateTime(), nullable=True),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["book.id"], name=op.f("fk_user_book_book_id_book")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_book_user_id_user")
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "book_id", name=op.f("pk_user_book")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_book")
    op.drop_table("profile")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_name"))

    op.drop_table("user")
    op.drop_table("signup_code")
    with op.batch_alter_table("message_board", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_board_name"))

    op.drop_table("message_board")
    with op.batch_alter_table("book", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_book_title"))
        batch_op.drop_index(batch_op.f("ix_book_author"))

    op.drop_table("book")
    # ### end Alembic commands ###
