name: Main Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        uses: actions/github-script@v7
        env:
          WEBHOOKURL: ${{ secrets.WEBHOOKURL }}
        with:
          script: |
            const notification = {
              msg_type: 'text',
              content: {
                text: `There has been a push to the main branch. Check the details at: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`
              }
            };
            fetch(process.env.WEBHOOKURL, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify(notification)
            });